# Generated by Django 3.1.2 on 2020-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Area',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='Humid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='Minimum',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='Name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='data',
            name='Rainfall',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='Soil',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
