# Generated by Django 3.1.2 on 2020-10-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_savedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Area',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='Minimum',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='Name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='Rainfall',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='Soil',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
